# Generated by Django 5.2 on 2026-07-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='カテゴリコード')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='商品コード')),
                ('jan_code', models.CharField(blank=True, max_length=20, verbose_name='JANコード')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='賞味期限（製造より○日）')),
                ('mall_limit_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='モール期限（残○日まで）')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stock.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='ReceiveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateField(verbose_name='入荷日')),
                ('expiry_date', models.DateField(verbose_name='賞味期限')),
                ('location', models.CharField(choices=[('store', '店頭'), ('warehouse', '倉庫')], max_length=20, verbose_name='入庫先')),
                ('quantity', models.IntegerField(verbose_name='入庫数')),
                ('remarks', models.CharField(blank=True, max_length=30, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_histories', to='stock.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '入庫履歴',
                'verbose_name_plural': '入庫履歴',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField(verbose_name='出荷日')),
                ('location', models.CharField(choices=[('store', '店頭'), ('warehouse', '倉庫')], max_length=20, verbose_name='出荷元')),
                ('quantity', models.PositiveIntegerField(verbose_name='出荷数')),
                ('remarks', models.CharField(blank=True, max_length=30, verbose_name='備考')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='確定済み')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_plans', to='stock.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '出庫予定',
                'verbose_name_plural': '出庫予定',
                'ordering': ['ship_date', 'product__product_code'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(verbose_name='賞味期限')),
                ('store_quantity', models.IntegerField(default=0, verbose_name='店頭在庫数')),
                ('warehouse_quantity', models.IntegerField(default=0, verbose_name='倉庫在庫数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='stock.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '在庫ロット',
                'verbose_name_plural': '在庫ロット',
                'ordering': ['expiry_date'],
            },
        ),
    ]
