# Generated by Django 5.2 on 2026-07-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivehistory',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確定日時'),
        ),
        migrations.AddField(
            model_name='receivehistory',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='確定済み'),
        ),
    ]
